spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://shopmall-mysql-master.shopmall:3306/shopmall_oms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: nacos-service.shopmall:8848
  application:
    name: shopmall-order
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    id-type: auto
server:
  port: 8080