spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3307/shopmall_oms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: shopmall-order
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    id-type: auto
server:
  port: 9000