kind: Deployment
apiVersion: app/v1
metadata:
  name: shopmall-search
  namespace: shopmall
  labels:
    app: shopmall-search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopmall-search
  template:
    metadata:
      labels:
        app: shopmall-search
    spec:
      containers:
        - name: shopmall-search
          image: $REGISTRY/$DOCKERHUB_NAMESPACE/$PROJECT_NAME:$PROJECT_VERSION
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 1000m
              memory: 500Mi
            requests:
              cpu: 10m
              memory: 10Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

---
kind: Service
apiVersion: v1
metadata:
  name: shopmall-search
  namespace: shopmall
  labels:
    app: shopmall-search
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 20015
  selector:
    app: shopmall-search
  type: NodePort
  sessionAffinity: None